"""Updated event and entries

Revision ID: 02507f8d6d6b
Revises: 81f474b6145d
Create Date: 2026-04-17 19:52:03.160253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02507f8d6d6b'
down_revision: Union[str, Sequence[str], None] = '81f474b6145d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('scheduled_at', sa.DateTime(), nullable=False))
    op.add_column('entry', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('entry', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.drop_column('entry', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('entry', 'finished_at')
    op.drop_column('entry', 'started_at')
    op.drop_column('entry', 'scheduled_at')
    # ### end Alembic commands ###
