"""Added relationship cascade delete

Revision ID: 649066688829
Revises: 9566f142003b
Create Date: 2026-04-01 09:51:52.574645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '649066688829'
down_revision: Union[str, Sequence[str], None] = '9566f142003b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entry_event_id_fkey'), 'entry', type_='foreignkey')
    op.create_foreign_key(None, 'entry', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.create_foreign_key(op.f('entry_event_id_fkey'), 'entry', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###
