"""flattned out the events

Revision ID: 739cb0ea5e39
Revises: 8c9fb8a3ca4d
Create Date: 2026-04-05 11:48:37.831557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '739cb0ea5e39'
down_revision: Union[str, Sequence[str], None] = '8c9fb8a3ca4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('entry', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.add_column('entry', sa.Column('phase_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entry', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('entry', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_entry_due_date'), 'entry', ['due_date'], unique=False)
    op.create_index(op.f('ix_entry_event_id'), 'entry', ['event_id'], unique=False)
    op.create_index(op.f('ix_entry_user_id'), 'entry', ['user_id'], unique=False)
    op.add_column('event', sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('event', 'blueprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('blueprint', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('event', 'phases')
    op.drop_index(op.f('ix_entry_user_id'), table_name='entry')
    op.drop_index(op.f('ix_entry_event_id'), table_name='entry')
    op.drop_index(op.f('ix_entry_due_date'), table_name='entry')
    op.alter_column('entry', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('entry', 'updated_at')
    op.drop_column('entry', 'phase_data')
    op.drop_column('entry', 'due_date')
    op.drop_column('entry', 'user_id')
    # ### end Alembic commands ###
