"""field's in events

Revision ID: 8c9fb8a3ca4d
Revises: 649066688829
Create Date: 2026-04-05 01:12:57.505559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c9fb8a3ca4d'
down_revision: Union[str, Sequence[str], None] = '649066688829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('event', sa.Column('rrule', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('event', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'timezone')
    op.drop_column('event', 'duration_minutes')
    op.drop_column('event', 'start_at')
    op.drop_column('event', 'rrule')
    op.drop_column('event', 'is_recurring')
    # ### end Alembic commands ###
