"""Added events

Revision ID: 9566f142003b
Revises: 88a84aed9a58
Create Date: 2026-03-30 15:42:29.417033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9566f142003b'
down_revision: Union[str, Sequence[str], None] = '88a84aed9a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('blueprint', sa.JSON(), nullable=True))
    op.add_column('event', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('event', 'validation_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('validation_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('event', 'is_active')
    op.drop_column('event', 'blueprint')
    # ### end Alembic commands ###
