"""updated entry create

Revision ID: a21b80ebcf5b
Revises: 8407bb2b9d74
Create Date: 2026-04-05 09:27:40.912899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a21b80ebcf5b'
down_revision: Union[str, Sequence[str], None] = '8407bb2b9d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'user_id')
    op.add_column('entry', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'user_id')
    # ### end Alembic commands ###
